name: whatsapp_camera
description: 'This is a package to open a camera along with a photo gallery, to simplify the steps of the end user'
version: 1.0.0
homepage: 'https://github.com/welitonsousa/whatsapp_camera'
repository: 'https://github.com/welitonsousa/whatsapp_camera'
issue_tracker: 'https://github.com/welitonsousa/whatsapp_camera/issues'
environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: '>=1.17.0'
dependencies:
  flutter:
    sdk: flutter
  camera_camera: ^3.0.0
  file_picker: ^8.0.0+1
  flutter_sliding_up_panel: 2.0.1
  photo_gallery: 1.1.1
  photo_view: 0.14.0
  permission_handler: 10.2.0
  image_gallery_saver: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: null
