name: whatsapp_camera
description: 'This is a package to open a camera along with a photo gallery, to simplify the steps of the end user'
version: 1.0.0
homepage: 'https://github.com/welitonsousa/whatsapp_camera'
repository: 'https://github.com/welitonsousa/whatsapp_camera'
issue_tracker: 'https://github.com/welitonsousa/whatsapp_camera/issues'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.5
  permission_handler: ^10.2.0
  image_gallery_saver: ^2.0.3
  camera: ^0.11.0+2
  path_provider: ^2.1.1
  path: ^1.9.0
  image: ^4.2.0
  native_device_orientation: ^1.1.9
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter: null
